### ISSUE TITLE
photos/pictures are not shown...

### ISSUE THREAD

**Issue by hugofant** [JC5/monica-multi-arch#1]
Hi,
installation worked well, login without a problem, but when adding photos, they were uploaded (and exists in directory /var/lib/docker/volumes/monica_data/_data/app/public/photos) but avatar is not show and photos are "empty".
a hint/solution would be great.

**Comment by JC5** [comment]
Thanks for letting me know. I never upload photo's so I wasn't aware of the issue. Allow me some time to investigate, I'll get back to you as soon as I have fix.

**Comment by JC5** [comment]
This is now fixed.
