### ISSUE TITLE
"more details" are not show, when adding activities

### ISSUE THREAD

**Issue by hugofant** [JC5/monica-multi-arch#2]
Hi again,
adding activities works well, but when selecting "Add more details" the data are not show afterwards.

**Comment by JC5** [comment]
I  see what you mean. I have no idea what's causing it. Stay tuned.

**Comment by JC5** [comment]
Sorry, I'm no longer monitoring or maintaining this image. I've disabled the repo and I'm going to remove the images from Docker hub. Please look elsewhere. Thank you.
