### ISSUE TITLE
when swithing language, dropdownboxes are still in english

### ISSUE THREAD

**Issue by hugofant** [JC5/monica-multi-arch#3]
Hi,
switching language works well, but when selecting from dropdown boxes, values are still in english.
a check direclty on db lebel showed, that there are no values in another language...as it looks good directly on "https://app.monicahq.com/" - how to load them?

**Comment by JC5** [comment]
I don't know. I can't replicate this issue. When I switch to another language, the app updates succesfully.

I don't know where in the DB you're looking though, could you show me?

**Comment by JC5** [comment]
Sorry, I'm no longer monitoring or maintaining this image. I've disabled the repo and I'm going to remove the images from Docker hub. Please look elsewhere. Thank you.
