### ISSUE TITLE
Image doesn't seem to work, the logs is empty

### ISSUE THREAD

**Issue by Luke-101** [JC5/monica-multi-arch#4]
So I've followed the tutorial on the README file but it doesn't seem to work.
In fact when i run "docker logs monica" it doesn't return anything, not even a error message.
When i try to connect behind reverse proxy i get: "HTTP ERROR 502" and with the local ip: "ERR_CONNECTION_REFUSED"

I also tried to executed from docker compose, to pass a normal path instead of monica_data
P.s. I tryed to execute it with the monica.env empty, default and configured but the result doesn't change

**Comment by JC5** [comment]
Sorry, I'm no longer monitoring or maintaining this image. I've disabled the repo and I'm going to remove the images from Docker hub. Please look elsewhere. Thank you.
